using System.Windows.Forms;
using System.Drawing;

namespace HospitalManagementSystem
{
    // =====================================================================
    // HospitalDashboard.Designer.cs
    // This file BUILDS all the visual controls (menus, toolbar, etc.)
    // In Visual Studio this is auto-generated by the drag-and-drop designer.
    // Here it is written manually so beginners can read and learn from it.
    // =====================================================================

    partial class HospitalDashboard
    {
        // Controls declared here so the whole class can use them
        private MenuStrip menuStrip;
        private ToolStrip toolStrip;
        private ContextMenuStrip contextMenuStrip;

        // Menu items
        private ToolStripMenuItem menuFile;
        private ToolStripMenuItem menuNewPatient;
        private ToolStripMenuItem menuNewDoctor;
        private ToolStripMenuItem menuNewBilling;
        private ToolStripMenuItem menuSeparator;
        private ToolStripMenuItem menuExit;

        private ToolStripMenuItem menuWindow;
        private ToolStripMenuItem menuCascade;
        private ToolStripMenuItem menuTileHorizontal;
        private ToolStripMenuItem menuTileVertical;

        // Toolbar buttons
        private ToolStripButton toolBtnPatient;
        private ToolStripButton toolBtnDoctor;
        private ToolStripButton toolBtnBilling;
        private ToolStripButton toolBtnArrange;

        // Right-click menu items
        private ToolStripMenuItem contextOpenPatient;
        private ToolStripMenuItem contextOpenDoctor;
        private ToolStripMenuItem contextCloseAll;

        /// <summary>
        /// InitializeComponent is called by the constructor.
        /// It creates and arranges every control on the form.
        /// </summary>
        private void InitializeComponent()
        {
            // ── Create objects ─────────────────────────────────────────────
            menuStrip       = new MenuStrip();
            toolStrip       = new ToolStrip();
            contextMenuStrip = new ContextMenuStrip();

            // ── MENUSTRIP ──────────────────────────────────────────────────

            // "File" top-level menu
            menuFile        = new ToolStripMenuItem("File");
            menuNewPatient  = new ToolStripMenuItem("New Patient");
            menuNewDoctor   = new ToolStripMenuItem("New Doctor");
            menuNewBilling  = new ToolStripMenuItem("New Billing");
            menuExit        = new ToolStripMenuItem("Exit");

            // Wire up click events for File menu items
            menuNewPatient.Click += menuNewPatient_Click;
            menuNewDoctor.Click  += menuNewDoctor_Click;
            menuNewBilling.Click += menuNewBilling_Click;
            menuExit.Click       += menuExit_Click;

            // Add items under File
            menuFile.DropDownItems.Add(menuNewPatient);
            menuFile.DropDownItems.Add(menuNewDoctor);
            menuFile.DropDownItems.Add(menuNewBilling);
            menuFile.DropDownItems.Add(new ToolStripSeparator()); // divider line
            menuFile.DropDownItems.Add(menuExit);

            // "Window" top-level menu
            menuWindow          = new ToolStripMenuItem("Window");
            menuCascade         = new ToolStripMenuItem("Cascade");
            menuTileHorizontal  = new ToolStripMenuItem("Tile Horizontal");
            menuTileVertical    = new ToolStripMenuItem("Tile Vertical");

            menuCascade.Click        += menuCascade_Click;
            menuTileHorizontal.Click += menuTileHorizontal_Click;
            menuTileVertical.Click   += menuTileVertical_Click;

            menuWindow.DropDownItems.Add(menuCascade);
            menuWindow.DropDownItems.Add(menuTileHorizontal);
            menuWindow.DropDownItems.Add(menuTileVertical);

            // Add top-level menus to the MenuStrip
            menuStrip.Items.Add(menuFile);
            menuStrip.Items.Add(menuWindow);

            // ── TOOLSTRIP (toolbar at the top) ─────────────────────────────
            toolBtnPatient = new ToolStripButton("👤 Patient Form");
            toolBtnDoctor  = new ToolStripButton("🩺 Doctor Form");
            toolBtnBilling = new ToolStripButton("💳 Billing Form");
            toolBtnArrange = new ToolStripButton("🪟 Arrange Windows");

            // Style the buttons
            toolBtnPatient.BackColor = Color.LightBlue;
            toolBtnDoctor.BackColor  = Color.LightGreen;
            toolBtnBilling.BackColor = Color.LightYellow;
            toolBtnArrange.BackColor = Color.LightSalmon;

            toolBtnPatient.Click += toolBtnPatient_Click;
            toolBtnDoctor.Click  += toolBtnDoctor_Click;
            toolBtnBilling.Click += toolBtnBilling_Click;
            toolBtnArrange.Click += toolBtnArrange_Click;

            toolStrip.Items.Add(toolBtnPatient);
            toolStrip.Items.Add(new ToolStripSeparator());
            toolStrip.Items.Add(toolBtnDoctor);
            toolStrip.Items.Add(new ToolStripSeparator());
            toolStrip.Items.Add(toolBtnBilling);
            toolStrip.Items.Add(new ToolStripSeparator());
            toolStrip.Items.Add(toolBtnArrange);

            // ── CONTEXT MENU STRIP (right-click menu) ─────────────────────
            contextOpenPatient = new ToolStripMenuItem("Open Patient Form");
            contextOpenDoctor  = new ToolStripMenuItem("Open Doctor Form");
            contextCloseAll    = new ToolStripMenuItem("Close All Windows");

            contextOpenPatient.Click += contextOpenPatient_Click;
            contextOpenDoctor.Click  += contextOpenDoctor_Click;
            contextCloseAll.Click    += contextCloseAll_Click;

            contextMenuStrip.Items.Add(contextOpenPatient);
            contextMenuStrip.Items.Add(contextOpenDoctor);
            contextMenuStrip.Items.Add(new ToolStripSeparator());
            contextMenuStrip.Items.Add(contextCloseAll);

            // Attach right-click menu to this form
            this.ContextMenuStrip = contextMenuStrip;

            // ── Add strips to the form ─────────────────────────────────────
            this.Controls.Add(menuStrip);
            this.Controls.Add(toolStrip);
            this.MainMenuStrip = menuStrip;
        }
    }
}
